server:
  port: 8081
# \u5E94\u7528\u540D\u79F0\uFF1Aclient
spring:
  application:
    name: client
# \u6CE8\u518C\u5230\u6211\u4EEC\u672C\u5730\u7684eureka\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u7AEF\u53E3\u662F8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
